version: '3'

services:
  app:
    image: node:ci
    command: ['npm', 'run', 'dev']
    volumes:
      - ../..:/opt/concourse-ci/task/app
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URI: postgresql://postgres:postgres@db:5432/db
      PAYLOAD_SECRET: mysecret
      NEXT_PUBLIC_SERVER_URL: http://localhost:3000
      PREVIEW_URL: http://localhost:5000
      OAUTH_CLIENT_ID: pages-client
      OAUTH_CLIENT_SECRET: client-secret
      OAUTH_AUTH_ENDPOINT: http://localhost:9001/oauth/authorize
      OAUTH_TOKEN_ENDPOINT: http://uaa:8080/oauth/token
      OAUTH_USERINFO_ENDPOINT: http://uaa:8080/userinfo
      LOGOUT_ENDPOINT: http://uaa:8080/logout.do
      PUBLIC_URL: http://localhost:3000
      PROMPT_URL: http://localhost:5000/reload
      TEST_DATABASE_URI: postgresql://postgres:postgres@db:5432/db
  db:
    image: postgres:ci
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db', '-h', 'db']
      interval: 10s
      timeout: 5s
      retries: 5
